/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData pdf = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnify_star = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safari = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logoutvariant = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageoutline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openinnew = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountoutline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData staroutline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountcircleoutline = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData halfchenvronright = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
